#!/bin/bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

# Target Directory
TD=$1
if [ -z "$TD" ]
then
  TD="dumps"
fi
mkdir $TD || true

# File prefix
PRE=$2
if [ -z "$PRE" ]
then
  PRE="dump"
fi


echo
echo "Time now: `date`"
echo

mkdir -p dumps
D=$(date +%Y%m%d%H%M%S)
DB=$(sed -n "s/define( *'DB_NAME', *'\([^']*\)'.*/\1/p" wp-config.php)
US=$(sed -n "s/define( *'DB_USER', *'\([^']*\)'.*/\1/p" wp-config.php)
PS=$(sed -n "s/define( *'DB_PASSWORD', *'\([^']*\)'.*/\1/p" wp-config.php)

F="$TD/$PRE-$DB_$D.sql.gz"
rm -f $F

mysqldump --no-tablespaces -u $US -p"$PS" $DB | gzip > $F

ls -lha $TD/ | grep $D
